pyprland.plugins = [ "scratchpads" ]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm-runner"
class = "kitty-dropterm-runner"
size = "75% 60%"
max_size = "75% 60%"
margin = 240

[scratchpads.btop]
animation = "fromTop"
command = "kitty --class kitty-btop btop"
class = "kitty-btop"
size = "75% 75%"
max_size = "75% 75%"
margin = 50
